### ISSUE TITLE
`rocks spins` broken

### ISSUE THREAD

**Issue by Siltala** [maxmahlke/rocks#11]
Hi,

The command `rocks spins` seems to fail with an error whenever an asteroid that has spin data available is queried. This used to work fine so there is a regression involved.

Example output:
```
$ rocks spins Ryugu
Traceback (most recent call last):
  File "/home/lauri/.local/lib/python3.10/site-packages/rocks/core.py", line 839, in __init__
    super().__init__(**ssocard)  # type: ignore
  File "pydantic/main.py", line 342, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 2 validation errors for Rock
spins -> period_flag -> 5
  value is not a valid float (type=type_error.float)
spins -> period_flag -> 9
  value is not a valid float (type=type_error.float)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lauri/.local/bin/rocks", line 8, in <module>
    sys.exit(cli_rocks())
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1651, in invoke
    cmd_name, cmd, args = self.resolve_command(ctx, args)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1698, in resolve_command
    cmd = self.get_command(ctx, cmd_name)
  File "/home/lauri/.local/lib/python3.10/site-packages/rocks/cli.py", line 44, in get_command
    return echo()
  File "/home/lauri/.local/lib/python3.10/site-packages/rocks/cli.py", line 340, in echo
    rock = core.Rock(id_, datacloud=catalogues, suppress_errors=not verbose)
  File "/home/lauri/.local/lib/python3.10/site-packages/rocks/core.py", line 872, in __init__
    del offending_part[error["loc"][-1]]
IndexError: list assignment index out of range
```

**Comment by maxmahlke** [comment]
Fixed in version 1.6.6. Thanks for reporting!
