### ISSUE TITLE
Building the name-number index assumes ~/.cache/rocks/index exists

### ISSUE THREAD

**Issue by Siltala** [maxmahlke/rocks#13]
With the fixes in #12  there is one lingering issue: building the name-number index fails with the following:

```
rocks status              

Contents of /home/lauri/.cache/rocks:

        0 ssoCards
        0 datacloud catalogues

Asteroid name-number index not available.
Checking if rocks is up-to-date.. the latest version (1.6.5) is installed.


Update the asteroid name-number index?
[0] No [1] Yes (1): 1

Building index ━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  14%
Traceback (most recent call last):
  File "/home/lauri/.local/bin/rocks", line 8, in <module>
    sys.exit(cli_rocks())
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/lauri/.local/lib/python3.10/site-packages/rocks/cli.py", line 248, in status
    index._build_index()
  File "/home/lauri/.local/lib/python3.10/site-packages/rocks/index.py", line 47, in _build_index
    task(index)
  File "/home/lauri/.local/lib/python3.10/site-packages/rocks/index.py", line 64, in _build_index_of_aliases
    _write_to_cache(aliases, "aliases.pkl")
  File "/home/lauri/.local/lib/python3.10/site-packages/rocks/index.py", line 261, in _write_to_cache
    with open(config.PATH_INDEX / filename, "wb") as file_:
FileNotFoundError: [Errno 2] No such file or directory: '/home/lauri/.cache/rocks/index/aliases.pkl'
```

It seems that `rocks` assumes that the `~/.cache/rocks/index` always exists, but when starting from an empty cache it does not.
Manually creating the folder itself works around this error

**Comment by maxmahlke** [comment]
Same solution as for #10.
