### ISSUE TITLE
`rocks albedos 2015_OS35` crashes

### ISSUE THREAD

**Issue by Siltala** [maxmahlke/rocks#15]
Hi Max,

With version 1.6.7 I'm still seeing a crash when fetching albedos for a specific asteroid - 2015_OS35.
Terminal output:

```
$ rocks albedos 2015_OS35
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3629, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 136, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 163, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'err_albedo_up'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lauri/.local/bin/rocks", line 8, in <module>
    sys.exit(cli_rocks())
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1651, in invoke
    cmd_name, cmd, args = self.resolve_command(ctx, args)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1698, in resolve_command
    cmd = self.get_command(ctx, cmd_name)
  File "/home/lauri/.local/lib/python3.10/site-packages/rocks/cli.py", line 44, in get_command
    return echo()
  File "/home/lauri/.local/lib/python3.10/site-packages/rocks/cli.py", line 350, in echo
    datacloud.pretty_print(rock, core.rgetattr(rock, param), param)
  File "/home/lauri/.local/lib/python3.10/site-packages/rocks/datacloud.py", line 100, in pretty_print
    *[str(catalogue[c][i]) if c else str(i + 1) for c in columns],
  File "/home/lauri/.local/lib/python3.10/site-packages/rocks/datacloud.py", line 100, in <listcomp>
    *[str(catalogue[c][i]) if c else str(i + 1) for c in columns],
  File "/usr/lib/python3.10/site-packages/pandas/core/frame.py", line 3505, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/usr/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3631, in get_loc
    raise KeyError(key) from err
KeyError: 'err_albedo_up'
```

**Comment by maxmahlke** [comment]
Great, you found an edge case! Fixed in 1.6.8.
