### ISSUE TITLE
` rocks albedos 6178` crashes

### ISSUE THREAD

**Issue by Siltala** [maxmahlke/rocks#17]
Hi Max,

I found another crash when looking up albedos for the asteroid 6178. with space-rocks 1.6.11.
Terminal output:

```
$ rocks albedos 6178
Traceback (most recent call last):
  File "/home/lauri/.local/bin/rocks", line 8, in <module>
    sys.exit(cli_rocks())
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1651, in invoke
    cmd_name, cmd, args = self.resolve_command(ctx, args)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1698, in resolve_command
    cmd = self.get_command(ctx, cmd_name)
  File "/home/lauri/.local/lib/python3.10/site-packages/rocks/cli.py", line 44, in get_command
    return echo()
  File "/home/lauri/.local/lib/python3.10/site-packages/rocks/cli.py", line 340, in echo
    rock = core.Rock(id_, datacloud=catalogues, suppress_errors=not verbose)
  File "/home/lauri/.local/lib/python3.10/site-packages/rocks/core.py", line 911, in __init__
    catalogue_instance = dc.DataCloudDataFrame(data=catalogue_dict)
  File "/usr/lib/python3.10/site-packages/pandas/core/frame.py", line 636, in __init__
    mgr = dict_to_mgr(data, index, columns, dtype=dtype, copy=copy, typ=manager)
  File "/usr/lib/python3.10/site-packages/pandas/core/internals/construction.py", line 502, in dict_to_mgr
    return arrays_to_mgr(arrays, columns, index, dtype=dtype, typ=typ, consolidate=copy)
  File "/usr/lib/python3.10/site-packages/pandas/core/internals/construction.py", line 120, in arrays_to_mgr
    index = _extract_index(arrays)
  File "/usr/lib/python3.10/site-packages/pandas/core/internals/construction.py", line 674, in _extract_index
    raise ValueError("All arrays must be of the same length")
ValueError: All arrays must be of the same length
```

**Comment by maxmahlke** [comment]
Hi Lauri,

indeed, it seems that the SsODNet datacloud table of diameters and albedos has an issue atm, see for example

https://ssp.imcce.fr/webservices/ssodnet/api/datacloud.php?-name=id:Robertpepin&-resource=diamalbedo&-mime=json&-from=SsODNetSsoCard

There are no albedo/diameter values in the diamalbedo entries. I notified Jerome about this.

And I will make rocks fail gracefully in this case.

**Comment by maxmahlke** [comment]
The datacloud catalogue issue has been fixed and the ingestion of catalogues in rocks.Rock instances is more reliable.
