### ISSUE TITLE
Suppress errors issue in command line

### ISSUE THREAD

**Issue by kateminker** [maxmahlke/rocks#19]
Hi Max!

I've been having a lot of errors with rocks in the command line, I think it's from the elimination of suppress_errors:

(base) kminker@pc-bcarry:~/c2pu-data$ rocks diameter 2020bx12
Traceback (most recent call last):
  File "/home/kminker/anaconda3/bin/rocks", line 8, in <module>
    sys.exit(cli_rocks())
  File "/home/kminker/anaconda3/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/kminker/anaconda3/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/kminker/anaconda3/lib/python3.9/site-packages/click/core.py", line 1653, in invoke
    cmd_name, cmd, args = self.resolve_command(ctx, args)
  File "/home/kminker/anaconda3/lib/python3.9/site-packages/click/core.py", line 1700, in resolve_command
    cmd = self.get_command(ctx, cmd_name)
  File "/home/kminker/anaconda3/lib/python3.9/site-packages/rocks/cli.py", line 44, in get_command
    return echo()
  File "/home/kminker/anaconda3/lib/python3.9/site-packages/rocks/cli.py", line 342, in echo
    rock = core.Rock(id_, datacloud=catalogues, suppress_errors=not verbose)
TypeError: __init__() got an unexpected keyword argument 'suppress_errors'

I get the same error for different asteroids and different parameters

Help

Kate

**Comment by maxmahlke** [comment]
You were right, there was a spurious `suppress_errors` left. Fixed in 1.6.16.

Thanks Kate!
