### ISSUE TITLE
`rocks spins` broken (for some asteroids)

### ISSUE THREAD

**Issue by Siltala** [maxmahlke/rocks#23]
Hi Max,

For some (not all) asteroids, `rocks spins` is currently crashing with version 1.7.3. I've spotted two different looking backtraces for the asteroids Ryugu and Orpheus (these are not the only ones to crash by far, but the other crashes have similar backtraces to one of the two). An example asteroid that works still is 2005 UD.

Terminal output for these cases follows:

```
$ rocks spins Ryugu
Traceback (most recent call last):
  File "/home/lauri/.local/lib/python3.10/site-packages/rocks/core.py", line 864, in __init__
    super().__init__(**ssocard)  # type: ignore
  File "pydantic/main.py", line 342, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 2 validation errors for Rock
spins -> period_flag -> 5
  value is not a valid float (type=type_error.float)
spins -> period_flag -> 8
  value is not a valid float (type=type_error.float)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lauri/.local/bin/rocks", line 8, in <module>
    sys.exit(cli_rocks())
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1651, in invoke
    cmd_name, cmd, args = self.resolve_command(ctx, args)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1698, in resolve_command
    cmd = self.get_command(ctx, cmd_name)
  File "/home/lauri/.local/lib/python3.10/site-packages/rocks/cli.py", line 45, in get_command
    return echo()
  File "/home/lauri/.local/lib/python3.10/site-packages/rocks/cli.py", line 347, in echo
    rock = core.Rock(id_, datacloud=catalogues)
  File "/home/lauri/.local/lib/python3.10/site-packages/rocks/core.py", line 898, in __init__
    super().__init__(**ssocard)  # type: ignore
  File "pydantic/main.py", line 342, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Rock
spins -> period_flag -> 7
  value is not a valid float (type=type_error.float)
  ```
  
  ```
  $ rocks spins Orpheus
Traceback (most recent call last):
  File "/home/lauri/.local/bin/rocks", line 8, in <module>
    sys.exit(cli_rocks())
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1651, in invoke
    cmd_name, cmd, args = self.resolve_command(ctx, args)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1698, in resolve_command
    cmd = self.get_command(ctx, cmd_name)
  File "/home/lauri/.local/lib/python3.10/site-packages/rocks/cli.py", line 45, in get_command
    return echo()
  File "/home/lauri/.local/lib/python3.10/site-packages/rocks/cli.py", line 347, in echo
    rock = core.Rock(id_, datacloud=catalogues)
  File "/home/lauri/.local/lib/python3.10/site-packages/rocks/core.py", line 920, in __init__
    catalogue_instance = dc.DataCloudDataFrame(data=catalogue_dict)
  File "/usr/lib/python3.10/site-packages/pandas/core/frame.py", line 664, in __init__
    mgr = dict_to_mgr(data, index, columns, dtype=dtype, copy=copy, typ=manager)
  File "/usr/lib/python3.10/site-packages/pandas/core/internals/construction.py", line 493, in dict_to_mgr
    return arrays_to_mgr(arrays, columns, index, dtype=dtype, typ=typ, consolidate=copy)
  File "/usr/lib/python3.10/site-packages/pandas/core/internals/construction.py", line 118, in arrays_to_mgr
    index = _extract_index(arrays)
  File "/usr/lib/python3.10/site-packages/pandas/core/internals/construction.py", line 666, in _extract_index
    raise ValueError("All arrays must be of the same length")
ValueError: All arrays must be of the same length
```

**Comment by maxmahlke** [comment]
Thanks Lauri! It seems that the `spins.period_flag` type changed from `int` to `str` in SsODNet. I changed it in `rocks`, fixed in version 1.7.5.
