### ISSUE TITLE
Feature request: include aliases/designations in Rock

### ISSUE THREAD

**Issue by Siltala** [maxmahlke/rocks#31]
Hi Max,

I'm working on some code for which I would like to get the designations of arbitrary named asteroids from within the rocks python module which, as far as I can tell, is not currently possible.

For example, when looking at Ryugu, I can easily get both the name and number but not the designation 1999 JU3, which is what I want in this context:
```
>>> x = Rock("Ryugu")
>>> x.number
162173
>>> x.name
'Ryugu'
>>> x.designation
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/.local/lib/python3.10/site-packages/rocks/core.py", line 1039, in __getattr__
    raise AttributeError(
AttributeError: 'Rock' object has no attribute 'designation'. Run 'rocks parameters' to get a list of accepted properties.
```

Running `rocks ids Ryugu` on the command line gets me the information I want but, as far as I can tell, it's not exposed anywhere in the python module. Would you mind implementing something among these lines? Presumably it would be straightforward to do since I see it's already possible to get this information through `resolve.identify`. If you want, I can also try to implement this myself.

**Comment by maxmahlke** [comment]
Hi Lauri! Making aliases accessible via the `Rock` class has been on my to-do list for quite a while, either as `Rock.ids` or `Rock.aliases`:

```python
>>> import rocks
>>> ceres = rocks.Rock(1)
>>> ceres.ids
[aliases of ceres]
```

So while your request fits perfectly (and I appreciate your offer to work on this!), unfortunately, it comes at a bad time. I am in the process of re-structuring the whole `resolve` module as `rocks` will soon support the name resolution of comets and natural satellites as well as asteroids. This is not an easy feat as the three groups have overlapping names, different naming conventions, and general requirements, and the name-resolution code is the most important part of `rocks`, so it needs to be done carefully. I could add the alias-lookup now but that change would soon be outdated in a new release, so I'd prefer to wait.

In the meantime, you could send queries to `SsODNet.quaero` directly to get the aliases, see here (or the code in the `resolve` module):

https://ssp.imcce.fr/webservices/ssodnet/api/quaero/

**Comment by bcarry** [comment]
Hi

Raising up this issue. I noted a bug in `rocks.identify`. The `return_aliases` has no effect unless `local` is set to False.

**Comment by maxmahlke** [comment]
Indeed, aliases require a quaero query as they are not stored locally. So `local=False` is required but was not yet forced. I fixed this now, `rocks.id(1, return_aliases=True)` forces a remote query and returns the aliases. Will be included in the next version, which I will probably push before ACM next Monday.
