### ISSUE TITLE
FileNotFoundError on first run

### ISSUE THREAD

**Issue by rszakats** [maxmahlke/rocks#39]
Hi!

I just installed rocks and I tried this as my first command:

(vegyes) rszakats@pc149:~/git/vegyes$ rocks author szakáts
Traceback (most recent call last):
  File "/data/munka/git/vegyes/vegyes/bin/rocks", line 8, in <module>
    sys.exit(cli_rocks())
             ^^^^^^^^^^^
  File "/data/munka/git/vegyes/vegyes/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/munka/git/vegyes/vegyes/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/data/munka/git/vegyes/vegyes/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/munka/git/vegyes/vegyes/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/munka/git/vegyes/vegyes/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/munka/git/vegyes/vegyes/lib/python3.11/site-packages/rocks/cli.py", line 69, in author
    metadata.find_author(name)
  File "/data/munka/git/vegyes/vegyes/lib/python3.11/site-packages/rocks/metadata.py", line 93, in find_author
    with open(config.PATH_AUTHORS, "w") as file_:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/rszakats/.cache/rocks/ssodnet_biblio.json'

As you can see there was a FileNotFoundError. 

After that I tried this:

(vegyes) rszakats@pc149:~/git/vegyes$ rocks id eris

And the program asked me to set a default cache directory and after that everything worked as expected.

So maybe it would be nice that despite what the first command is the program's first action were to initialize the cache directory.

**Comment by maxmahlke** [comment]
Hi @rszakats, thanks for reporting this! You are right, `rocks` assumed that the first query is asteroid-related and only then created the cache directory. I just pushed version `1.9.9` to fix this behaviour. Cheers!
