### ISSUE TITLE
Updating name-number index fails

### ISSUE THREAD

**Issue by Siltala** [maxmahlke/rocks#40]
Hi Max,

I noticed that there's a problem with updating the cache / name-number index as of recently - attempting to do so leads to a crash.
This is with rocks 1.9.9 which I know is not the latest version, but 1.9.10 has not been uploaded to pypi for some reason (another bug? :) ) so I have not tried it - feel free to just close if you have already fixed this.
 
Traceback and terminal output below:

```
$ rocks status         

Contents of /home/ubuntu/.cache/rocks:

        0 ssoCards
        0 datacloud catalogues

        
        Index updated on:  [No Index Found]

Checking if rocks is up-to-date..
The running rocks version (1.9.9) is behind the latest version (1.9.10).
You should run $ pip install -U space-rocks and clear the cache directory.


Update the asteroid name-number index?
[0] No [1] Yes (1): 1

Processing 1,368,399 minor bodies... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━  80%
                  Gardening Regolith ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0%
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.10/concurrent/futures/process.py", line 246, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/rocks/index.py", line 116, in _build_number_index
    parts = np.arange(1, np.ceil(numbered.Number.max() / SIZE) * SIZE, SIZE, dtype=int)
  File "missing.pyx", line 392, in pandas._libs.missing.NAType.__bool__
TypeError: boolean value of NA is ambiguous
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/rocks", line 8, in <module>
    sys.exit(cli_rocks())
  File "/home/ubuntu/.local/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/rocks/cli.py", line 241, in status
    index._build_index()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/rocks/index.py", line 91, in _build_index
    future.result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
TypeError: boolean value of NA is ambiguous
```

**Comment by maxmahlke** [comment]
Hi Lauri, thanks for reporting this. It turns out that all `number` values in the SsODNet index file that is created explicitly for `rocks` are `0` this week. We're fixing that. In the meantime, it's best not to update the index at all.

**Comment by maxmahlke** [comment]
File fixed and updated, you can go ahead updating again!
